[2025-05-21T17:43:06.844+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-21T17:43:06.903+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_car_5_tg_err.load_to_greenplum scheduled__2025-05-20T00:00:00+00:00 [queued]>
[2025-05-21T17:43:06.932+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_car_5_tg_err.load_to_greenplum scheduled__2025-05-20T00:00:00+00:00 [queued]>
[2025-05-21T17:43:06.934+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-05-21T17:43:06.981+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_to_greenplum> on 2025-05-20 00:00:00+00:00
[2025-05-21T17:43:07.013+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=604) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-21T17:43:07.016+0000] {standard_task_runner.py:72} INFO - Started process 613 to run task
[2025-05-21T17:43:07.010+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_car_5_tg_err', 'load_to_greenplum', 'scheduled__2025-05-20T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/test_car_5 _tg_err.py', '--cfg-path', '/tmp/tmpqf3tg56n']
[2025-05-21T17:43:07.034+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask load_to_greenplum
[2025-05-21T17:43:07.267+0000] {task_command.py:467} INFO - Running <TaskInstance: test_car_5_tg_err.load_to_greenplum scheduled__2025-05-20T00:00:00+00:00 [running]> on host 0562d356b684
[2025-05-21T17:43:07.678+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_car_5_tg_err' AIRFLOW_CTX_TASK_ID='load_to_greenplum' AIRFLOW_CTX_EXECUTION_DATE='2025-05-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-20T00:00:00+00:00'
[2025-05-21T17:43:07.682+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-21T17:43:07.770+0000] {test_car_5 _tg_err.py:229} INFO - >>> [START] load_to_greenplum
[2025-05-21T17:43:07.920+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2025-05-21T17:43:08.421+0000] {test_car_5 _tg_err.py:59} INFO - Telegram notification sent successfully
[2025-05-21T17:43:08.424+0000] {test_car_5 _tg_err.py:305} INFO - Successfully loaded 45/45 records to GreenPlum
[2025-05-21T17:43:08.441+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-21T17:43:08.471+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-21T17:43:08.472+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_car_5_tg_err, task_id=load_to_greenplum, run_id=scheduled__2025-05-20T00:00:00+00:00, execution_date=20250520T000000, start_date=20250521T174306, end_date=20250521T174308
[2025-05-21T17:43:08.568+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-21T17:43:08.619+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-21T17:43:08.630+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
