[2025-05-22T13:36:45.488+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-22T13:36:45.642+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_car_5_tg.load_to_postgres manual__2025-05-22T13:35:58.098270+00:00 [queued]>
[2025-05-22T13:36:45.702+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_car_5_tg.load_to_postgres manual__2025-05-22T13:35:58.098270+00:00 [queued]>
[2025-05-22T13:36:45.704+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-05-22T13:36:45.753+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2025-05-22 13:35:58.098270+00:00
[2025-05-22T13:36:45.775+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=191) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-22T13:36:45.780+0000] {standard_task_runner.py:72} INFO - Started process 193 to run task
[2025-05-22T13:36:45.782+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_car_5_tg', 'load_to_postgres', 'manual__2025-05-22T13:35:58.098270+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/test_car_5 _tg.py', '--cfg-path', '/tmp/tmp1gtcii_6']
[2025-05-22T13:36:45.789+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask load_to_postgres
[2025-05-22T13:36:45.926+0000] {task_command.py:467} INFO - Running <TaskInstance: test_car_5_tg.load_to_postgres manual__2025-05-22T13:35:58.098270+00:00 [running]> on host 3d98b42a4b31
[2025-05-22T13:36:46.231+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_car_5_tg' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-05-22T13:35:58.098270+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-22T13:35:58.098270+00:00'
[2025-05-22T13:36:46.234+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-22T13:36:46.280+0000] {test_car_5 _tg.py:231} INFO - >>> [START] load_to_postgres
[2025-05-22T13:36:46.353+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2025-05-22T13:36:47.043+0000] {test_car_5 _tg.py:59} INFO - Telegram notification sent successfully
[2025-05-22T13:36:47.064+0000] {test_car_5 _tg.py:307} INFO - Successfully loaded 45/45 records to postgres
[2025-05-22T13:36:47.086+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-22T13:36:47.169+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-22T13:36:47.172+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_car_5_tg, task_id=load_to_postgres, run_id=manual__2025-05-22T13:35:58.098270+00:00, execution_date=20250522T133558, start_date=20250522T133645, end_date=20250522T133647
[2025-05-22T13:36:47.308+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-22T13:36:47.369+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-22T13:36:47.375+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
